<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>

<script>
  // 1. setTimeout
  /*setTimeout(() => {
    console.log('Hello World');
  }, 1000)*/

  // 参数是一个函数(resolve, reject)
  // resolve、reject本事又是一个函数
  /*new Promise((resolve, reject) => {
    setTimeout(() => {
      console.log('Hello World');
      console.log('Hello World');
      console.log('Hello World');
      console.log('Hello World');

      setTimeout(() => {
        console.log('Hello Vuejs');
        console.log('Hello Vuejs');
        console.log('Hello Vuejs');
        console.log('Hello Vuejs');

        setTimeout(() => {
          console.log('Hello Python');
          console.log('Hello Python');
          console.log('Hello Python');
          console.log('Hello Python');
        }, 1000)

      }, 1000)
    }, 1000)
  })*/
  // 2. 使用Promise
  /*new Promise((resolve, reject) => {
    // 第一次网络请求的代码
    setTimeout(() => {
      resolve()
    }, 1000)
  }).then(() => {
    // 第一次结果处理的代码
    console.log('Hello World');
    console.log('Hello World');
    console.log('Hello World');
    console.log('Hello World');

    return new Promise((resolve, reject) => {
      // 第二次网路请求的代码
      setTimeout(() => {
        resolve()
      }, 1000)
    })
  }).then(() =>{
    // 第二次结果处理的代码
    console.log('Hello Vuejs');
    console.log('Hello Vuejs');
    console.log('Hello Vuejs');
    console.log('Hello Vuejs');

    return new Promise((resolve, reject) => {
      // 第三次网络请求的代码
      setTimeout(() => {
        resolve()
      }, 1000)
    })
  }).then(() => {
    // 第三次结果处理的代码
    console.log('Hello Python');
    console.log('Hello Python');
    console.log('Hello Python');
    console.log('Hello Python');
  })*/

  // 什么情况下会使用Promise？
  // 一般情况下是有异步操作时，使用Promise对这个异步操作进行封装
  // new -> 构造函数(1.保存一些状态信息 2.执行要传入的函数)
  // 在执行传入的回调函数时，会传入两个参数，resolve、reject，本身又是函数
  new Promise((resolve, reject) => {
    setTimeout(() => {
      // 成功的时候调用resolve
      // resolve('Hello World')

      // 失败的时候调用reject
      reject('error')
    }, 1000)
  }).then(data => {
    // 成功处理
    // 执行100行代码
    console.log(data);
    console.log(data);
    console.log(data);
  }).catch(err => {
    // 失败处理
    console.log(err);
  })
</script>
</body>
</html>